project_id = "prmpzclkdjtrphsemrgm"

[functions.polish-transcript]
verify_jwt = false

[functions.potemkin-chat]
verify_jwt = false

[functions.send-campaign-email]
verify_jwt = false

[functions.email-unsubscribe]
verify_jwt = false

[functions.zhukovsky]
verify_jwt = false

[functions.factcheck]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
