// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prmpzclkdjtrphsemrgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBybXB6Y2xrZGp0cnBoc2VtcmdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5MjM5NDcsImV4cCI6MjA5MTQ5OTk0N30.d5EU_OFwMdl72G_Ew9j5qSrvC5GEpK0xMiZkychPeZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});