// Database types for the A-Level Russia revision app.
//
// NOTE: this file used to be auto-generated by Supabase CLI against the old
// project (lcbqiuufbrjilkzzmvjd), which only had a single `content_reports`
// table. We've replaced it with the full schema for the new project
// (prmpzclkdjtrphsemrgm), hand-written to match `_rebuild/01_supabase/schema.sql`.
//
// If you ever regenerate this file via the Supabase CLI, double check that it
// still reflects every table and that you've re-exported the generic helpers
// at the bottom — the data hooks rely on them.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// ---------- Domain JSONB shapes ---------------------------------------------

export type RecallSummary = {
  sections: Array<{
    heading: string
    content: string[]
  }>
}

export type KeyConcept = {
  concept: string
  trigger_keywords: string[]
}

export type PerQuestionEntry = {
  question_id: string
  question_text: string
  user_input?: string
  result: 'correct' | 'incorrect' | 'spot_on' | 'right_idea' | 'missed'
}

export type ConceptResult = {
  concept: string
  covered: boolean
}

export type ChronologySequenceItem = {
  event: string
  date: string
}

// ---------- Database ---------------------------------------------------------

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      // --------- Content tables (public read) -------------------------------
      spec_points: {
        Row: {
          id: number
          part: number
          section: string
          title: string
          short_title: string | null
          ko_file: string | null
          sort_order: number
        }
        Insert: {
          id: number
          part: number
          section: string
          title: string
          short_title?: string | null
          ko_file?: string | null
          sort_order: number
        }
        Update: Partial<Database['public']['Tables']['spec_points']['Insert']>
        Relationships: []
      }

      recall_content: {
        Row: {
          spec_id: number
          summary: RecallSummary
          key_concepts: KeyConcept[]
        }
        Insert: {
          spec_id: number
          summary: RecallSummary
          key_concepts: KeyConcept[]
        }
        Update: Partial<Database['public']['Tables']['recall_content']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'recall_content_spec_id_fkey'
            columns: ['spec_id']
            referencedRelation: 'spec_points'
            referencedColumns: ['id']
          }
        ]
      }

      exam_questions: {
        Row: {
          id: string
          year: string
          section: string
          question_number: string | null
          question_type: string | null
          marks: number | null
          question_text: string
          spec_ids: number[]
          indicative_content: string | null
          source_files: Json | null
          time_period: string | null
        }
        Insert: {
          id: string
          year: string
          section: string
          question_number?: string | null
          question_type?: string | null
          marks?: number | null
          question_text: string
          spec_ids: number[]
          indicative_content?: string | null
          source_files?: Json | null
          time_period?: string | null
        }
        Update: Partial<Database['public']['Tables']['exam_questions']['Insert']>
        Relationships: []
      }

      extract_vault: {
        Row: {
          id: string
          year: string
          section: string
          question_number: string | null
          question_type: string | null
          marks: number | null
          question_text: string
          spec_ids: number[]
          indicative_content: string | null
          source_files: Json | null
          time_period: string | null
        }
        Insert: {
          id: string
          year: string
          section: string
          question_number?: string | null
          question_type?: string | null
          marks?: number | null
          question_text: string
          spec_ids: number[]
          indicative_content?: string | null
          source_files?: Json | null
          time_period?: string | null
        }
        Update: Partial<Database['public']['Tables']['extract_vault']['Insert']>
        Relationships: []
      }

      fact_questions: {
        Row: {
          id: string
          spec_id: number
          question: string
          answer: string
          valid_synonyms: string[]
          source: string | null
          created_at: string
        }
        Insert: {
          id?: string
          spec_id: number
          question: string
          answer: string
          valid_synonyms?: string[]
          source?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['fact_questions']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'fact_questions_spec_id_fkey'
            columns: ['spec_id']
            referencedRelation: 'spec_points'
            referencedColumns: ['id']
          }
        ]
      }

      concept_questions: {
        Row: {
          id: string
          legacy_id: string | null
          spec_id: number
          question_type: string | null
          question_text: string
          correct_answer: string
          ko_terms_used: string[]
          good_answer_synonym: string | null
          workpack_ref: string | null
          textbook_ref: string | null
          source: string | null
          created_at: string
        }
        Insert: {
          id?: string
          legacy_id?: string | null
          spec_id: number
          question_type?: string | null
          question_text: string
          correct_answer: string
          ko_terms_used?: string[]
          good_answer_synonym?: string | null
          workpack_ref?: string | null
          textbook_ref?: string | null
          source?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['concept_questions']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'concept_questions_spec_id_fkey'
            columns: ['spec_id']
            referencedRelation: 'spec_points'
            referencedColumns: ['id']
          }
        ]
      }

      chronology_questions: {
        Row: {
          id: string
          mode: 'place_in_time' | 'identify' | 'sequence'
          question_text: string
          correct_part: number | null
          correct_answer: string | null
          sequence_data: ChronologySequenceItem[] | null
          hint_date: string | null
          source: string | null
          created_at: string
        }
        Insert: {
          id?: string
          mode: 'place_in_time' | 'identify' | 'sequence'
          question_text: string
          correct_part?: number | null
          correct_answer?: string | null
          sequence_data?: ChronologySequenceItem[] | null
          hint_date?: string | null
          source?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['chronology_questions']['Insert']>
        Relationships: []
      }

      // --------- User data tables (owner-based RLS) -------------------------
      user_profiles: {
        Row: {
          id: string
          email: string | null
          full_name: string | null
          display_name: string | null
          role: 'student' | 'teacher'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email?: string | null
          full_name?: string | null
          display_name?: string | null
          role?: 'student' | 'teacher'
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['user_profiles']['Insert']>
        Relationships: []
      }

      user_sessions: {
        Row: {
          id: string
          user_id: string
          activity_type:
            | 'knowledge_driller'
            | 'concept_driller'
            | 'blank_recall'
            | 'chronology_place'
            | 'chronology_identify'
            | 'chronology_sequence'
          spec_id: number | null
          started_at: string
          completed_at: string | null
          total_questions: number | null
          correct_count: number | null
          per_question: PerQuestionEntry[]
          metadata: Json
        }
        Insert: {
          id?: string
          user_id: string
          activity_type:
            | 'knowledge_driller'
            | 'concept_driller'
            | 'blank_recall'
            | 'chronology_place'
            | 'chronology_identify'
            | 'chronology_sequence'
          spec_id?: number | null
          started_at?: string
          completed_at?: string | null
          total_questions?: number | null
          correct_count?: number | null
          per_question?: PerQuestionEntry[]
          metadata?: Json
        }
        Update: Partial<Database['public']['Tables']['user_sessions']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'user_sessions_spec_id_fkey'
            columns: ['spec_id']
            referencedRelation: 'spec_points'
            referencedColumns: ['id']
          }
        ]
      }

      user_wrong_answers: {
        Row: {
          id: string
          user_id: string
          question_table: 'fact_questions' | 'concept_questions'
          question_id: string
          spec_id: number | null
          question_snapshot: Json
          missed_at: string
          resolved_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          question_table: 'fact_questions' | 'concept_questions'
          question_id: string
          spec_id?: number | null
          question_snapshot: Json
          missed_at?: string
          resolved_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['user_wrong_answers']['Insert']>
        Relationships: []
      }

      user_blank_recalls: {
        Row: {
          id: string
          user_id: string
          spec_id: number
          written_text: string
          ai_feedback: string | null
          concepts_total: number | null
          concepts_covered: number | null
          concept_results: ConceptResult[]
          submitted_at: string
        }
        Insert: {
          id?: string
          user_id: string
          spec_id: number
          written_text: string
          ai_feedback?: string | null
          concepts_total?: number | null
          concepts_covered?: number | null
          concept_results?: ConceptResult[]
          submitted_at?: string
        }
        Update: Partial<Database['public']['Tables']['user_blank_recalls']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'user_blank_recalls_spec_id_fkey'
            columns: ['spec_id']
            referencedRelation: 'spec_points'
            referencedColumns: ['id']
          }
        ]
      }

      // --------- Class management -------------------------------------------
      classes: {
        Row: {
          id: string
          teacher_id: string
          name: string
          join_code: string
          created_at: string
        }
        Insert: {
          id?: string
          teacher_id: string
          name: string
          join_code: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['classes']['Insert']>
        Relationships: []
      }

      class_members: {
        Row: {
          id: string
          class_id: string
          student_id: string
          joined_at: string
        }
        Insert: {
          id?: string
          class_id: string
          student_id: string
          joined_at?: string
        }
        Update: Partial<Database['public']['Tables']['class_members']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'class_members_class_id_fkey'
            columns: ['class_id']
            referencedRelation: 'classes'
            referencedColumns: ['id']
          }
        ]
      }

      // --------- Question review pipeline -----------------------------------
      question_review_queue: {
        Row: {
          id: string
          spec_id: number
          target_table: 'fact_questions' | 'concept_questions'
          question_data: Json
          source: string
          status: 'pending' | 'approved' | 'rejected'
          rejection_reason: string | null
          submitted_by: string | null
          submitted_at: string
          reviewed_by: string | null
          reviewed_at: string | null
        }
        Insert: {
          id?: string
          spec_id: number
          target_table: 'fact_questions' | 'concept_questions'
          question_data: Json
          source?: string
          status?: 'pending' | 'approved' | 'rejected'
          rejection_reason?: string | null
          submitted_by?: string | null
          submitted_at?: string
          reviewed_by?: string | null
          reviewed_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['question_review_queue']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'question_review_queue_spec_id_fkey'
            columns: ['spec_id']
            referencedRelation: 'spec_points'
            referencedColumns: ['id']
          }
        ]
      }

      // --------- Student content reports ------------------------------------
      content_reports: {
        Row: {
          id: string
          created_at: string
          section: string
          topic_name: string
          original_text: string
          issue_type: string
          student_comment: string
          resolved: boolean
          reporter_id: string | null
          spec_id: number | null
        }
        Insert: {
          id?: string
          created_at?: string
          section: string
          topic_name: string
          original_text?: string
          issue_type: string
          student_comment?: string
          resolved?: boolean
          reporter_id?: string | null
          spec_id?: number | null
        }
        Update: Partial<Database['public']['Tables']['content_reports']['Insert']>
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_teacher: {
        Args: Record<string, never>
        Returns: boolean
      }
      join_class_by_code: {
        Args: { p_join_code: string }
        Returns: string
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// ---------- Generic helpers (same shapes as the old generated file) ---------

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
